apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../busybox

patches:
  - target:
      kind: PersistentVolumeClaim
      name: ubi-persistent
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-cephfs
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteMany