---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubi-persistent
  labels:
    appname: ubi-persistent
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi